development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: ripae
  username: quipuapp
  password: quipuapp123
  pool: 25

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: ripae_test
  username: quipuapp
  password: quipuapp123
  pool: 25
